version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: yo_pg
    environment:
      POSTGRES_DB: yocampus
      POSTGRES_USER: yoadmin
      POSTGRES_PASSWORD: yoadmin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
